import { requireAuth, checkTeamAccess, handleApiError, ApiError } from '@/lib/api-utils';
import { connectToDatabase } from '@/lib/db';
import {
  TeamMember,
  User,
  Team,
  TeamInvite,
  Group,
  SubGroup,
  Task,
  Message,
  DirectMessage,
  Notification,
  Activity
} from '@/lib/models';
import { createSupabaseServerClient } from '@/lib/auth';
import { NextRequest, NextResponse } from 'next/server';

// PUT update member role
export async function PUT(
  req: NextRequest,
  props: { params: Promise<{ teamId: string; userId: string }> }
) {
  try {
    const { teamId, userId } = await props.params;
    const user = await requireAuth(req);

    await connectToDatabase();
    await checkTeamAccess(user.id, teamId, 'admin');

    const body = await req.json();
    const { role } = body;

    if (!['admin', 'manager', 'member'].includes(role)) {
      throw new ApiError(400, 'Invalid role');
    }

    const member = await TeamMember.findOneAndUpdate(
      { team_id: teamId, user_id: userId },
      { role },
      { new: true }
    );

    if (!member) {
      throw new ApiError(404, 'Team member not found');
    }

    return NextResponse.json({ member });
  } catch (error) {
    return handleApiError(error);
  }
}

// DELETE remove member and clean up all their records
export async function DELETE(
  req: NextRequest,
  props: { params: Promise<{ teamId: string; userId: string }> }
) {
  try {
    const { teamId, userId } = await props.params;
    const user = await requireAuth(req);

    await connectToDatabase();
    await checkTeamAccess(user.id, teamId, 'admin');

    // Can't remove yourself
    if (user.id === userId) {
      throw new ApiError(400, 'Cannot remove yourself from team');
    }

    // Retrieve the target user document to get email and verify existence
    const targetUser = await User.findOne({ id: userId });
    if (!targetUser) {
      throw new ApiError(404, 'User not found');
    }
    const userEmail = targetUser.email;

    // Check if the user is the owner of any team
    const ownedTeam = await Team.findOne({ owner_id: userId });
    if (ownedTeam) {
      throw new ApiError(
        400,
        `Cannot remove the team owner of "${ownedTeam.name}". Please transfer ownership or delete the team first.`
      );
    }

    // Delete user from Supabase Auth
    try {
      const supabase = await createSupabaseServerClient();
      const { error: authError } = await supabase.auth.admin.deleteUser(userId);
      if (authError) {
        console.error(`[DELETE MEMBER] Supabase deleteUser error for ${userId}:`, authError);
      }
    } catch (supabaseErr) {
      console.error('[DELETE MEMBER] Supabase Client initialization/call error:', supabaseErr);
    }

    // Perform MongoDB cascading deletions:
    // 1. Delete user profile
    await User.deleteOne({ id: userId });

    // 2. Delete all team memberships
    await TeamMember.deleteMany({ user_id: userId });

    // 3. Remove user from all groups/channels
    await Group.updateMany(
      { members: userId },
      { $pull: { members: userId } }
    );

    // 4. Remove user from all sub-groups
    await SubGroup.updateMany(
      { members: userId },
      { $pull: { members: userId } }
    );

    // 5. Unassign tasks assigned to this user
    await Task.updateMany(
      { assigned_to: userId },
      { $unset: { assigned_to: '' } }
    );

    // 6. Delete channel and sub-group messages sent by the deleted member
    await Message.deleteMany({ sender_id: userId });

    // 7. Delete direct messages sent by them or any conversations involving them
    await DirectMessage.deleteMany({
      $or: [
        { sender_id: userId },
        { conversation_id: { $regex: userId } }
      ]
    });

    // 8. Delete notifications recipient/actor matches
    await Notification.deleteMany({
      $or: [
        { recipient_id: userId },
        { actor_id: userId }
      ]
    });

    // 9. Delete activity log entries generated by them
    await Activity.deleteMany({ user_id: userId });

    // 10. Delete invites matching their email or created by them
    await TeamInvite.deleteMany(
      userEmail
        ? { $or: [{ email: userEmail }, { created_by: userId }] }
        : { created_by: userId }
    );

    return NextResponse.json({ success: true });
  } catch (error) {
    return handleApiError(error);
  }
}

